project:
  type: book
  output-dir: docs
  
book:
  title: "Introduction to Machine Learning for Economists"
  author: "Taro Mieno"
  # cover-image: images/cover.png
  site-url: https://rstudio-education.github.io/hopr/
  repo-url: https://github.com/tmieno2/ML-Economist
  repo-branch: master
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - preface.qmd
    - part: basics.qmd
      chapters: 
        - bias-variance-tradeoff.qmd
        - cross-validation.qmd
        - lasso.qmd
        - bootstrap.qmd
    - part: prediction-ml.qmd
      chapters: 
        - tree-based-ml.qmd
    - part: causal-ml.qmd
      chapters: 
        - cf.qmd
  appendices:
    - mc-simulation.qmd
    - reticulate.qmd

format:
  html: 
    theme: cosmo
    # cover-image: cover.png
    code-link: true

