project:
  type: book
  output-dir: docs
  
book:
  title: "Introduction to Machine Learning for Economists"
  author: "Taro Mieno"
  # cover-image: images/cover.png
  site-url: https://rstudio-education.github.io/hopr/
  repo-url: https://github.com/tmieno2/ML-Economist
  repo-branch: master
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - preface.qmd
    - part: basics.qmd
      chapters: 
        - B01-gam.qmd
        - B02-bias-variance-tradeoff.qmd
        - B03-lasso.qmd
        - B04-cross-validation.qmd
        - B05-bootstrap.qmd
    - part: prediction-ml.qmd
      chapters: 
        - P01-random-forest.qmd
        - P02-boosted-regression-forest.qmd
        - P03-xgb.qmd
    - part: causal-ml.qmd
  #     chapters: 
  #       - cf.qmd
  appendices:
    - A01-mc-simulation.qmd
  #   - reticulate.qmd

bibliograph: ref.bib

format:
  html: 
    theme: cosmo
    code-link: true

