project:
  type: book
  output-dir: docs
  
book:
  title: "Introduction to Machine Learning for Economists"
  author: "Taro Mieno"
  # cover-image: images/cover.png
  site-url: https://tmieno2.github.io/ML-Economist/
  repo-url: https://github.com/tmieno2/ML-Economist
  repo-branch: master
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - H00-preface.qmd
    - text: "---"
    - part: B0P-basics.qmd
      chapters: 
        - B01-nonlinear.qmd
        - B02-bias-variance-tradeoff.qmd
        - B03-cross-validation.qmd
        - B04-regularization.qmd
        - B05-bootstrap.qmd
    - text: "---"
    - part: P0P-prediction-ml.qmd
      chapters: 
        - P01-random-forest.qmd
        - P02-boosted-regression-forest.qmd
        - P03-xgb.qmd
    - text: "---"
    - part: C0P-causal-ml.qmd
      chapters: 
        - C00-why-not-this.qmd
        - C01-dml.qmd
        - C02-r-learner.qmd
    - text: "---"
    - part: E0P-extensions.qmd
      chapters:
        - E01-spatial-cv.qmd
        - E02-grf.qmd
    - text: "---"
    - part: PROG-00-programming.qmd
      chapters:
        - PROG-01-mlr3.qmd
        - PROG-02-reticulate.qmd
        - PROG-03-model-selection-prediction.qmd
    - text: "---"
  appendices:
    - A01-mc-simulation.qmd

bibliography: ref.bib

format:
  html: 
    include-in-header:
      - analytics.html
    theme: cosmo
    code-link: true

execute:
  warning: false
  message: false

