project:
  type: book
  output-dir: docs
  
book:
  title: "Introduction to Machine Learning for Economists"
  author: "Taro Mieno"
  # cover-image: images/cover.png
  site-url: https://tmieno2.github.io/ML-Economist/
  repo-url: https://github.com/tmieno2/ML-Economist
  repo-branch: master
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - preface.qmd
    - part: basics.qmd
      chapters: 
        - B01-nonlinear.qmd
        - B02-bias-variance-tradeoff.qmd
        - B03-cross-validation.qmd
        - B04-regularization.qmd
        - B05-bootstrap.qmd
    - part: prediction-ml.qmd
      chapters: 
        - P01-random-forest.qmd
        - P02-boosted-regression-forest.qmd
        - P03-xgb.qmd
    - part: C00-causal-ml.qmd
      chapters: 
        - C01-dml.qmd
    - part: extensions.qmd
      chapters:
        - E01-spatial-cv.qmd
  appendices:
    - A01-mc-simulation.qmd
  #   - reticulate.qmd

bibliography: ref.bib

format:
  html: 
    include-in-header:
      - analytics.html
    theme: cosmo
    code-link: true

