# Causal Machine Learning (CML) Methods {.unnumbered}


:::{.callout-important}
+ the use of causal machine learning model does not guarantee you the estimate you got is indeed a causal effect (model itself does not have any ability) 
+ it always comes with an assumption 
+ CML is not a panacea at all. How can it be better than the traditional approaches?
  * may be able to capture complex non-linear interactions of variables without specifying how they interact
  * robust to specification errors
  * (can be less efficient)

:::


Unlike prediction-oriented machine learning (POML) methods, the focus of causal machine learning (CML) methods is to identify the heterogenous treatment effects of a treatment (or small number of distinct treatments). 

$$
TE(X) = \theta(X)\cdot T
$$

$\theta(X)$ is the impact of the treatment when $T$ is binary and marginal impact of the treatment when $T$ is continuous. $\theta(X)$ is a function of attributes ($X$), meaning that the impact of the treatment varies (heterogeneous) based on the value of the attributes. 

::: {.column-margin}
$T$ is 0 if not treated, 1 if treated.
:::

CML considers the following model (following [the documentation of the `econml` Python package](https://econml.azurewebsites.net/spec/estimation/dml.html))

$$
\begin{aligned}
Y & = \theta(X)\cdot T + g(X, W) + \varepsilon \\
T & = f(X, W) + \eta 
\end{aligned}
$$

$W$ are the collection of attributes that affect $Y$ along with $X$ (represented by $g(X, W)$), but not as drivers of the heterogeneity in the impact of the treatment. $X$ not just affects $Y$ as drivers of the heterogeneity in the impact of the treatment ($\theta(X)\cdot T$), but also directly along with $W$. 

Both $X$ and $W$ are potential confounders. While we do control for them (eliminating their influence) by partialing out $f(X, W)$ and $g(X, W)$, the sole focus is on the estimation of $\theta(X)$. This is in stark contrast to the focus of the ML methods we have seen in earlier sections, which primarily focuses on the accurate prediction of the <span style="color:blue"> level</span> of the dependent variable, rather than how the level of the dependent variable <span style="color:blue"> changes </span> when treated like CML methods.

Understanding the how treatment effects vary can be highly valuable in many circumstances. 

<span style="color:blue"> Example 1: </span>
If we come to know a particular drug is effective on elderly people but detrimental to kids, then doctors can make a smart decision of prescribing the drug to elderly people, but not to kids. 

::: {.column-margin}
In this example, the heterogeneity driver ($X$) is age.
:::

<span style="color:blue"> Example 3: </span>
If we come to know fertilizer is more effective in increasing corn yield in soil type A than B, then farmers can apply more fertilized on the parts of the field where soil type is A but less on where soil type is B. 

::: {.column-margin}
In this example, the heterogeneity driver ($X$) is soil type.
:::

As you can see these examples, knowledge on the heterogeneity of the treatment effects and its causes can help decision makers smart-target the treatment. 

